### ISSUE TITLE
Simultaneous multipath and single path sessions 

### ISSUE THREAD

**Issue by dboljira** [mkheirkhah/amp#1]
Hi  Morteza,

Thank you for the great contribution of MPTCP in ns-3. 

I have a problem to simulate multipath and single path flows in the same network to understand fair share of a capacity of MPTCP and TCP. Independent simulation is alright. I have tried to use different port and IP address for MPTCP and TCP but still, the simulation fails. Some how MPTCP advertises all IP and port setup for the node. Can you please comment on how to simulate such cases. 

It is this global configuration that causes the problem 

Config::SetDefault("ns3::TcpL4Protocol::SocketType",TypeIdValue(MpTcpSocketBase::GetTypeId()));

Is there a way to also have some TCP variant flows say TcpNewReno when MPTCP session is simulated? 

Thanks,

**Comment by mkheirkhah** [comment]
You can use MPTCP with single subflow to model single-path TCP, so you do not need to change the SocketType globally in your simulation script.
